### ISSUE TITLE
Can't run the game

### ISSUE THREAD

**Issue by MrBn100ful** [2000Slash/Minecraft2D#2]
Hello,
I have try to run the game but it's not working.
I have a blue windows :
![ss 2017-06-03 at 12 59 31](https://cloud.githubusercontent.com/assets/9916074/26752989/9790df7e-485c-11e7-9744-76749403a517.jpg)

Thanks.

**Comment by 2000Slash** [comment]
This will happen, if the game can't find the assets folder. If you look in the console it should also say, that it doesn't find the image files. The assets folder has to be in the same place as the jar file.
